In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cross_validation import train_test_split
import keras
from keras.layers import *
%matplotlib inline

C:\Users\HP.DESKTOP-UCJPQBV\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
C:\Users\HP.DESKTOP-UCJPQBV\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
df = pd.read_csv("F:\\python\\foresttype\\train.csv")
testset = pd.read_csv("F:\\python\\foresttype\\test.csv")

In [3]:
df.head()

Id  Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
0   1       2596      51      3                               258   
1   2       2590      56      2                               212   
2   3       2804     139      9                               268   
3   4       2785     155     18                               242   
4   5       2595      45      2                               153   

   Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
0                               0                              510   
1                              -6                              390   
2                              65                             3180   
3                             118                             3090   
4                              -1                              391   

   Hillshade_9am  Hillshade_Noon  Hillshade_3pm     ...      Soil_Type32  \
0            221             232            148     ...                0   
1            220             235            151     ...                0   
2            234             238            135     ...                0   
3            238             238            122     ...                0   
4            220             234            150     ...                0   

   Soil_Type33  Soil_Type34  Soil_Type35  Soil_Type36  Soil_Type37  \
0            0            0            0            0            0   
1            0            0            0            0            0   
2            0            0            0            0            0   
3            0            0            0            0            0   
4            0            0            0            0            0   

   Soil_Type38  Soil_Type39  Soil_Type40  Cover_Type  
0            0            0            0           5  
1            0            0            0           5  
2            0            0            0           2  
3            0            0            0           2  
4            0            0            0           5  

[5 rows x 56 columns]

In [4]:
testset.head()

Id  Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
0  15121       2680     354     14                                 0   
1  15122       2683       0     13                                 0   
2  15123       2713      16     15                                 0   
3  15124       2709      24     17                                 0   
4  15125       2706      29     19                                 0   

   Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
0                               0                             2684   
1                               0                             2654   
2                               0                             2980   
3                               0                             2950   
4                               0                             2920   

   Hillshade_9am  Hillshade_Noon  Hillshade_3pm     ...       Soil_Type31  \
0            196             214            156     ...                 0   
1            201             216            152     ...                 0   
2            206             208            137     ...                 0   
3            208             201            125     ...                 0   
4            210             195            115     ...                 0   

   Soil_Type32  Soil_Type33  Soil_Type34  Soil_Type35  Soil_Type36  \
0            0            0            0            0            0   
1            0            0            0            0            0   
2            0            0            0            0            0   
3            0            0            0            0            0   
4            0            0            0            0            0   

   Soil_Type37  Soil_Type38  Soil_Type39  Soil_Type40  
0            0            0            0            0  
1            0            0            0            0  
2            0            0            0            0  
3            0            0            0            0  
4            0            0            0            0  

[5 rows x 55 columns]

Save the ID column of the testset, which is used at submission.

In [117]:
ids = testset['Id']

Remove Id column as it has no significance.

In [118]:
df = df.drop('Id',axis = 1)
testset = testset.drop('Id',axis = 1)

In [119]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15120 entries, 0 to 15119
Data columns (total 55 columns):
Elevation                             15120 non-null int64
Aspect                                15120 non-null int64
Slope                                 15120 non-null int64
Horizontal_Distance_To_Hydrology      15120 non-null int64
Vertical_Distance_To_Hydrology        15120 non-null int64
Horizontal_Distance_To_Roadways       15120 non-null int64
Hillshade_9am                         15120 non-null int64
Hillshade_Noon                        15120 non-null int64
Hillshade_3pm                         15120 non-null int64
Horizontal_Distance_To_Fire_Points    15120 non-null int64
Wilderness_Area1                      15120 non-null int64
Wilderness_Area2                      15120 non-null int64
Wilderness_Area3                      15120 non-null int64
Wilderness_Area4                      15120 non-null int64
Soil_Type1                            15120 non-null int64
Soil_T

Check for null values. Looks like we have no null values.

In [120]:
df.isnull().sum()

Elevation                             0
Aspect                                0
Slope                                 0
Horizontal_Distance_To_Hydrology      0
Vertical_Distance_To_Hydrology        0
Horizontal_Distance_To_Roadways       0
Hillshade_9am                         0
Hillshade_Noon                        0
Hillshade_3pm                         0
Horizontal_Distance_To_Fire_Points    0
Wilderness_Area1                      0
Wilderness_Area2                      0
Wilderness_Area3                      0
Wilderness_Area4                      0
Soil_Type1                            0
Soil_Type2                            0
Soil_Type3                            0
Soil_Type4                            0
Soil_Type5                            0
Soil_Type6                            0
Soil_Type7                            0
Soil_Type8                            0
Soil_Type9                            0
Soil_Type10                           0
Soil_Type11                           0


In [121]:
testset.isnull().sum()

Elevation                             0
Aspect                                0
Slope                                 0
Horizontal_Distance_To_Hydrology      0
Vertical_Distance_To_Hydrology        0
Horizontal_Distance_To_Roadways       0
Hillshade_9am                         0
Hillshade_Noon                        0
Hillshade_3pm                         0
Horizontal_Distance_To_Fire_Points    0
Wilderness_Area1                      0
Wilderness_Area2                      0
Wilderness_Area3                      0
Wilderness_Area4                      0
Soil_Type1                            0
Soil_Type2                            0
Soil_Type3                            0
Soil_Type4                            0
Soil_Type5                            0
Soil_Type6                            0
Soil_Type7                            0
Soil_Type8                            0
Soil_Type9                            0
Soil_Type10                           0
Soil_Type11                           0


Lets check if any column has no values/not significant

In [122]:
df.sum()

Elevation                             41569757
Aspect                                 2368951
Slope                                   249504
Horizontal_Distance_To_Hydrology       3435199
Vertical_Distance_To_Hydrology          772277
Horizontal_Distance_To_Roadways       25916031
Hillshade_9am                          3216089
Hillshade_Noon                         3310760
Hillshade_3pm                          2042591
Horizontal_Distance_To_Fire_Points    22848547
Wilderness_Area1                          3597
Wilderness_Area2                           499
Wilderness_Area3                          6349
Wilderness_Area4                          4675
Soil_Type1                                 355
Soil_Type2                                 623
Soil_Type3                                 962
Soil_Type4                                 843
Soil_Type5                                 165
Soil_Type6                                 650
Soil_Type7                                   0
Soil_Type8   

In [123]:
testset.sum()

Elevation                             1677856995
Aspect                                  88069522
Slope                                    7944917
Horizontal_Distance_To_Hydrology       153105828
Vertical_Distance_To_Hydrology          26197635
Horizontal_Distance_To_Roadways       1339547352
Hillshade_9am                          120043311
Hillshade_Noon                         126440094
Hillshade_3pm                           80768040
Horizontal_Distance_To_Fire_Points    1127724419
Wilderness_Area1                          257199
Wilderness_Area2                           29385
Wilderness_Area3                          247015
Wilderness_Area4                           32293
Soil_Type1                                  2676
Soil_Type2                                  6902
Soil_Type3                                  3861
Soil_Type4                                 11553
Soil_Type5                                  1432
Soil_Type6                                  5925
Soil_Type7          

So, soiltype 7 and 15 has no values in it, that means none of the 7 cover types has a soiltype of 7 and 15, so lets these two from the list, as they have no real use.

In [124]:
df = df.drop(['Soil_Type7', 'Soil_Type15'],axis =1)
testset = testset.drop(['Soil_Type7', 'Soil_Type15'],axis =1)


Soiltype 8 and 25 has only one observation each, so lets check what those are.

In [125]:
df[df['Soil_Type8'] == 1]

Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
497       2900     180      3                               300   

     Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
497                              -2                             4725   

     Hillshade_9am  Hillshade_Noon  Hillshade_3pm  \
497            220             241            156   

     Horizontal_Distance_To_Fire_Points     ...      Soil_Type32  Soil_Type33  \
497                                4880     ...                0            0   

     Soil_Type34  Soil_Type35  Soil_Type36  Soil_Type37  Soil_Type38  \
497            0            0            0            0            0   

     Soil_Type39  Soil_Type40  Cover_Type  
497            0            0           2  

[1 rows x 53 columns]

In [126]:
df[df['Soil_Type25'] == 1]

Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
10605       3293     125     28                               108   

       Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
10605                             -37                              633   

       Hillshade_9am  Hillshade_Noon  Hillshade_3pm  \
10605            253             208             63   

       Horizontal_Distance_To_Fire_Points     ...      Soil_Type32  \
10605                                3728     ...                0   

       Soil_Type33  Soil_Type34  Soil_Type35  Soil_Type36  Soil_Type37  \
10605            0            0            0            0            0   

       Soil_Type38  Soil_Type39  Soil_Type40  Cover_Type  
10605            0            0            0           2  

[1 rows x 53 columns]

So, both the soiltypes 8 and 25 are for only Covertype 2. So, I think we can remove these columns also. But first lets run our model with these two columns

I want to try neural networks on this data, since we have a lot of numerical data.
We need to scale the data to (0,1) for the better results in neural networks

In [127]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range = (0,1))

Lets create our labels

In [128]:
labels = df.Cover_Type

Lets convert the labels to one hot format which is preferred for labels. 
There are many ways to do, i chose the one below

In [129]:
labels = pd.get_dummies(labels)

Convert to numpy array, since NN's accept numpy arrays only

In [130]:
labels = labels.values

Lets create our features matrix

In [131]:
features = df.drop('Cover_Type',axis =1)

In [132]:
features.shape

(15120, 52)

In [133]:
testset.shape # since we dont have the covertype already.

(565892, 52)

In [134]:
features = features.values

In [135]:
testset = testset.values

Heres the snapshot of features 

In [136]:
features[0]

array([2596,   51,    3,  258,    0,  510,  221,  232,  148, 6279,    1,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    1,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0], dtype=int64)

In [137]:
testset[0]

array([2680,  354,   14,    0,    0, 2684,  196,  214,  156, 6645,    1,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    1,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0], dtype=int64)

As we discussed, NN's work better on the data which is scaled. So lets scale our data.

In [138]:
features = scaler.fit_transform(features)

C:\Users\HP.DESKTOP-UCJPQBV\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [139]:
testset = scaler.transform(testset)

Here's how it looks after normalization/scaling.

In [140]:
features[0]

array([0.36908359, 0.14166667, 0.05769231, 0.19210722, 0.20857143,
       0.07402032, 0.87007874, 0.85806452, 0.59677419, 0.8978979 ,
       1.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       1.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ])

In [141]:
testset[0]

array([0.41137966, 0.98333333, 0.26923077, 0.        , 0.20857143,
       0.38955007, 0.77165354, 0.74193548, 0.62903226, 0.95023595,
       1.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       1.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ])

In [142]:
print(type(labels))
print(type(features))
print(type(testset))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


Lets split our dataset into testset and trainset

In [143]:
train_x,test_x,train_y,test_y = train_test_split(features,labels)

In [144]:
print(train_x.shape,train_y.shape,test_x.shape,test_y.shape)

(11340, 52) (11340, 7) (3780, 52) (3780, 7)


# KERAS

In [159]:
model = keras.models.Sequential()
model.add(Dense(300,input_dim = 52,activation = 'relu'))
model.add(Dense(700,activation = 'relu'))
model.add(Dense(200,activation = 'relu'))
model.add(Dense(7,activation='softmax'))
model.compile(loss = 'categorical_crossentropy',optimizer = 'adam',metrics = ['categorical_accuracy'])
model.fit(train_x,train_y,epochs=60,shuffle=True, verbose =1)

Epoch 1/60
11340/11340 [==============================] - 3s 297us/step - loss: 0.9097 - categorical_accuracy: 0.6288
Epoch 2/60
11340/11340 [==============================] - 3s 270us/step - loss: 0.7257 - categorical_accuracy: 0.6929
Epoch 3/60
11340/11340 [==============================] - 3s 265us/step - loss: 0.6660 - categorical_accuracy: 0.7117
Epoch 4/60
11340/11340 [==============================] - 3s 260us/step - loss: 0.6297 - categorical_accuracy: 0.7346
Epoch 5/60
11340/11340 [==============================] - 3s 254us/step - loss: 0.6039 - categorical_accuracy: 0.7394
Epoch 6/60
11340/11340 [==============================] - 3s 253us/step - loss: 0.5778 - categorical_accuracy: 0.7588
Epoch 7/60
11340/11340 [==============================] - 3s 266us/step - loss: 0.5556 - categorical_accuracy: 0.7685
Epoch 8/60
11340/11340 [==============================] - 3s 272us/step - loss: 0.5225 - categorical_accuracy: 0.7781
Epoch 9/60
11340/11340 [==============================] 

In [105]:
print("The Accuracy on the sampled test set is", model.evaluate(test_x,test_y)[1])

3780/3780 [==============================] - 0s 64us/step
The Accuracy on the sampled test set is 0.8552910052910053


So, lets now run the same keras model on the whole train set (on whole features) and predict the testset.

In [146]:
modelmain = keras.models.Sequential()
modelmain.add(Dense(300,input_dim = 52,activation = 'relu'))
modelmain.add(Dense(700,activation = 'relu'))
modelmain.add(Dense(200,activation = 'relu'))
modelmain.add(Dense(7,activation='softmax'))
modelmain.compile(loss = 'categorical_crossentropy',optimizer = 'adam',metrics = ['categorical_accuracy'])
modelmain.fit(features,labels,epochs=120,shuffle=True, verbose =0) #verbose 0 to display no logs

In [147]:
pred = modelmain.predict(testset)

In [149]:
covertype = [np.argmax(i)+1 for i in pred]

In [153]:
sub = pd.DataFrame({'Id':ids,'Cover_Type':covertype})

In [156]:
output = sub[['Id','Cover_Type']]

In [157]:
output.to_csv("output.csv",index = False)

# PLEASE UPVOTE, IF YOU LIKE IT.